### ISSUE TITLE
[BUG] Aethersteel template weight at 3/1053 or 0.28%

### ISSUE THREAD

**Issue by abint** [Ross2750/Aethersteel#2]
**Version**
Forge Version _(47.1.47)_
Mod Version _(4.9)_

**How to reproduce**
Mine suspicious aetherslate and account for drops. The drop rate is 0.28% or almost 1/333 for an Aethersteel template

**Expected behavior**
Expected behavior is 3/100 according to your description, but the weight in `data.aethersteel.loot_tables.blocks.suspicious_aetherslate.json` has a 3 roll out of 1053 possible weights.

The "weight" of aetherslate templates should be x10 that it is now to be close to a 3% drop.

Note: "weight" is **NOT PERCENTAGE** but instead how entries in a pool it gets. Imagine it like you have a hat with `100 coal, 95 bones, 90 name tags, 85 gunpowder, 80 flower pots,  75 bricks, 70 paper, 65 maps, 60 sticks,  55 clay balls, 50 feathers, 45 diamonds, 40 gold nuggets, 35 iron pickaxes, 30 chainmail chests, 25 mushroom stews, 20 emeralds, 15 golden appless, 10 thing patterns, 5 totems of undying, & 3 aethersteel templates` and you're allowed to pull only 1 item. There are 1053 items, and only 3 are aetherslate templates.

**Comment by Ross2750** [comment]
Sorry I will gonna edit the description and I will put 1% instead
