### ISSUE TITLE
[BUG] Can't update or remove breaks world

### ISSUE THREAD

**Issue by Ki-Tan2934** [Ross2750/Aethersteel#4]
**Version**
Forge Version _(eg. 43.1.43)_
Mod Version _4.9_

**How to reproduce**
Update to 5.0 or remove mod

**Expected behavior**
This should not happen

**Screenshots**
[](https://imgur.com/a/tjbsaPB)

**Comment by Ross2750** [comment]
Sorry but I can't understand you, do you mean Aetherslate cave is missing?

**Comment by Ki-Tan2934** [comment]
https://imgur.com/a/tjbsaPB

I posted a link but it defaults to using MD so the Title was blank so not viewable...

**Comment by Ki-Tan2934** [comment]
> Sorry but I can't understand you, do you mean Aetherslate cave is missing?

No Updating the mod or removing the mod breaks worlds

**Comment by Ki-Tan2934** [comment]
pack is https://legacy.curseforge.com/minecraft/modpacks/pixelbcg/files/4819882 encase you want to test it for yourself

**Comment by Ross2750** [comment]
Okay I will check if v5.0 have a problem and I will update you

**Comment by Ross2750** [comment]
I think it caused some issues because Aethersteel Tweaks was installed and that mod removes the Aetherslate Cave biome but that cave biome was removed in v5.0.

**Comment by Ki-Tan2934** [comment]
> I think it caused some issues because Aethersteel Tweaks was installed and that mod removes the Aetherslate Cave biome but that cave biome was removed in v5.0. Aethersteel Tweaks should not be used in Aethersteel v5.0

No, this happened on the previous version, Aethersteel Tweaks was installed to change the mod.

Please install the version before Aether tweaks were added, make a world then update the mod and try and load into that world

**Comment by Ross2750** [comment]
I tried Aethersteel with Aethersteel Tweaks and it works fine but that mod is useless on v5.0. Maybe the other mods in that modpack causing that issue

**Comment by Ki-Tan2934** [comment]
I'm not fully sure all I know is that after making a world on version 4.9 I'm unable to update the mod or remove it with out getting the message in the screenshot I linked before

**Comment by Ki-Tan2934** [comment]
So far only Aethersteel has that problem

**Comment by Ki-Tan2934** [comment]
I'm happy to not use Aethersteel Tweaks but I would need to update your mod and if possible I don't want to have to break worlds

**Comment by Ross2750** [comment]
The worlds breaks because I removed the cave biome in v5.0. I'm gonna find a solution how to fix that

**Comment by Ross2750** [comment]
I release a new update that fixes this issue

**Comment by Ross2750** [comment]
I release a new update that fixes this issue
