### ISSUE TITLE
Mining Level Aetherslate mixup

### ISSUE THREAD

**Issue by Staegrin** [Ross2750/Aethersteel#5]
**Version**
NeoForge Version 47.1.76
Mod Version Aethersteel-v5.1-1.20.1
                    theoneprobe-1.20.1-10.0.1

**How to reproduce**
The Oneprobe clearly states that the mining level of Aetherslate is Iron Level
![2023-11-05_14 35 01](https://github.com/Ross2750/Aethersteel/assets/8494635/dfbc9159-81c7-4577-8a46-837017a323f8)
![2023-11-05_14 35 24](https://github.com/Ross2750/Aethersteel/assets/8494635/d1d08b6b-8cb7-4ebd-a493-d47b0e1cf4c9)
But when mined with an iron pickaxe the block is destroyed instead.
Using a diamond pickaxe drops the block
![2023-11-05_14 35 59](https://github.com/Ross2750/Aethersteel/assets/8494635/ffc14eda-98ce-4a25-bbcc-ff0cf75e25dd)

**Expected behavior**
Either the messages says the mining level is diamond or an iron pickaxe can mine aetherslate.

**Comment by Ross2750** [comment]
I guess that's a bug with oneprobe because Aetherslate is set to Diamond Pickaxe

**Comment by Staegrin** [comment]
Thanks for letting me know. Guess I'll go notify them.

**Comment by Staegrin** [comment]
McJty said "just using the levels reported to be my Minecraft and TOP is correct for obsidian". Maybe something isn't being marked correctly towards the client.

**Comment by Ross2750** [comment]
I don't really know if I can fix this issue

**Comment by Staegrin** [comment]
I can only report the bug. Don't know enough coding to help. Keep up the good work.
