### ISSUE TITLE
[BUG] CTD when equipping any Aethersteel armour piece

### ISSUE THREAD

**Issue by sprocketaudio** [Ross2750/Aethersteel#7]
**Version**
Forge Version 43.3.7
Mod Version 5.4 - 1.19.2

**How to reproduce**
Equip any aethersteel armour piece

**Expected behavior**
The game shouldn't CTD

[latest.log](https://github.com/Ross2750/Aethersteel/files/14279525/latest.log)
[crash-2024-02-14_12.40.10-server.txt](https://github.com/Ross2750/Aethersteel/files/14279526/crash-2024-02-14_12.40.10-server.txt)

**Comment by Mr-Zombii** [comment]
I have fixed that bug in a personal decompilation & deobfuscation project of this mod https://github.com/Mr-Zombii/AetherSteel for forge 1.19.2

release: https://github.com/Mr-Zombii/AetherSteel/releases/tag/FORGE-1.19.2-1.0

**Comment by sprocketaudio** [comment]
ahh thanks but unless its on curse I cant use it in my modpack :(

I hope this gets fixed officially!

**Comment by sprocketaudio** [comment]
> I have fixed that bug in a personal decompilation & deobfuscation project of this mod https://github.com/Mr-Zombii/AetherSteel for forge 1.19.2
> 
> release: https://github.com/Mr-Zombii/AetherSteel/releases/tag/FORGE-1.19.2-1.0

do you know is this something I can fix with datapack or no?

**Comment by Mr-Zombii** [comment]
Yes it it something you can fix with a datapack and also I have uploaded the datapack to curse and modrinth and is currently under review.

**Comment by Mr-Zombii** [comment]
https://github.com/Mr-Zombii/AetherSteel/releases/tag/Datapack-1.19.X

**Comment by Pantheris2019** [comment]
Well, even though the datapack is a workaround, the CTD should need to be fixed within the mod itself, meaning it needs to be updated.  The reason I am commenting is that I am also experiencing the same issue.

**Comment by Ross2750** [comment]
Hello there! I came back from modding again, are you all using a 1.19.2 version of aethersteel?

**Comment by Ross2750** [comment]
I need someone to test 1.19.2 version of Aethersteel to check if the CTD was fixed

**Comment by Ross2750** [comment]
@sprocketaudio Can you try using [this version](https://1drv.ms/u/c/1ab88badbaf868c7/ERVHN134EUZIl7fpSoMRq_YBzmHzO9JcbbaPNMT2l23QjA?e=FiVpDm)?
If the issue was fixed I will release this version to public.

**Comment by sprocketaudio** [comment]
Sure I will test today thanks!

**Comment by Ross2750** [comment]
> Sure I will test today thanks!

Any updates?

**Comment by sprocketaudio** [comment]
Working, and the achi pops when u get all 4. ty!

**Comment by Ross2750** [comment]
Thanks! just wait until it get released and added to the modpacks
