### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Asuna3244** [Ross2750/Aethersteel#8]
**Version**
Forge Version _(eg. 47.2.20)_
Mod Version _(5.4)_

I send the server log. There you will find the error code

https://paste.modularity.gg/paste/?content=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F768367574001778729%2F1211381975319973908%2Flatest.log&raw=false

**Comment by Mr-Zombii** [comment]
That error is only just says that you don't have the optional dependencies listed on cursed forge and the github readme.md
